### ISSUE TITLE
Getting warnings about missing src files

### ISSUE THREAD

**Issue by smurfy** [yuyang041060120/ng2-validation#1]
I get a warning for each validator similiar to this:

```
./~/ng2-validation/dist/index.js
Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in '/var/www/moo/node_modules/ng2-validation/dist'
```

My guess is that the src folder is missing in the npm install

**Comment by yuyang041060120** [comment]
@smurfy can you offer more information? Because my testing works fine.

**Comment by smurfy** [comment]
Sure, i use angular-cli, master (due the  webpack and easier less suppport) and angular rc4.

If you install the ng2-validation npm package it does not include the src directory, only the dist folder is present.
I think in the "map" files (due to the weekend i have no access to my code) still include files from the src directory. causing angular-cli / webpack to raise warnings, which will be displayed on the browser console and in the local angular-cli serve server.

I think its only affects development but it's quite bad because it shows a long warning for each .js file from the dist directory. obscuring (you have to scroll a lot) other errors or debug output.

**Comment by yuyang041060120** [comment]
I tested with angular-cli. It still worked fine. Here are the changed files of my testing.

_angular-cli-build.js_ 

add ng2-validation to vendor

``` javascript
module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(ts|js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      'ng2-validation/**/*.+(ts|js|js.map)'
    ]
  });
};
```

_src/system-config.ts_

edit `barrels` and `map`

``` javascript
const barrels:string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/forms',
  '@angular/http',
  '@angular/router',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  'ng2-validation'
  /** @cli-barrel */
];

const cliSystemConfigPackages:any = {};
barrels.forEach((barrelName:string) => {
  cliSystemConfigPackages[barrelName] = {main: 'index'};
});

/** Type declaration for ambient System. */
declare var System:any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'ng2-validation': 'vendor/ng2-validation/dist',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});
```

_src/main.ts_

add new form module

``` javascript
import {bootstrap} from '@angular/platform-browser-dynamic';
import {enableProdMode} from '@angular/core';
import {disableDeprecatedForms, provideForms} from '@angular/forms';
import {AppComponent, environment} from './app/';

if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms()
]);
```

_src/app/app.component.ts_

import ng2-validation directives

``` javascript
import {Component} from '@angular/core';

import {CUSTOM_FORM_DIRECTIVES, CustomValidators} from 'ng2-validation';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [CUSTOM_FORM_DIRECTIVES]
})
export class AppComponent {
  title = 'app works!';
}
```

_src/app/app.component.html_

add json validator

``` html
<h1>
  {{title}}

  <form action="" #form="ngForm">
    <input type="text" ngModel #name="ngModel" name="name" json>
    <p *ngIf="name?.errors?.json">json error</p>
  </form>
</h1>
```

**Comment by smurfy** [comment]
I will try tomorrow with your changes to `angular-cli-build.js` and `src/system-config.ts`, i did not need these to get the validation itself working. But maybe they will fix the warnings for me.

If the changes do not help, i will create a new default angular 2 project using the same angular-cli i'm using to hopefully allow you to reproduce the warnings.

**Comment by yuyang041060120** [comment]
@smurfy It's my pleasure to help.

**Comment by smurfy** [comment]
Here the version which throws the warnings:

https://github.com/smurfy/ng2-validation-warnings

My guess is webpack which is uses with the latest (master) version of angular-cli.
I think you are still using the non webpack version (`angular-cli-build.js`got removed for example)

**Comment by yuyang041060120** [comment]
@smurfy It was fixed. you can reinstall and try again.

**Comment by smurfy** [comment]
Thank you, works
