### ISSUE TITLE
does not export CustomFormsModule error

### ISSUE THREAD

**Issue by jigsaxis** [yuyang041060120/ng2-validation#10]
Hi, I have install lib. but it's giving following error

\node_modules\ng2-validation\dist\index.js does not export CustomFormsModule (imported by C:\MyApp.tmp\app\app.module.js)

**Comment by yuyang041060120** [comment]
@jigsaxis can you show more details?

**Comment by elmoromourad** [comment]
zone.js:1382 GET http://localhost:3002/ng2-validation 404 (Not Found)scheduleTask @ zone.js:1382ZoneDelegate.scheduleTask @ zone.js:245Zone.scheduleMacroTask @ zone.js:171(anonymous function) @ zone.js:1405send @ VM5420:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:518(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:232Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339XMLHttpRequest.send (async)scheduleTask @ zone.js:1382ZoneDelegate.scheduleTask @ zone.js:245Zone.scheduleMacroTask @ zone.js:171(anonymous function) @ zone.js:1405send @ VM5420:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:518(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:232Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339XMLHttpRequest.send (async)scheduleTask @ zone.js:1382ZoneDelegate.scheduleTask @ zone.js:245Zone.scheduleMacroTask @ zone.js:171(anonymous function) @ zone.js:1405send @ VM5420:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:518(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:232Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401Promise.resolve (async)scheduleQueueDrain @ zone.js:374scheduleMicroTask @ zone.js:382ZoneDelegate.scheduleTask @ zone.js:248Zone.scheduleMicroTask @ zone.js:168scheduleResolveOrReject @ zone.js:500ZoneAwarePromise.then @ zone.js:586(anonymous function) @ system.src.js:4663import @ system.src.js:872(anonymous function) @ system.src.js:1762(anonymous function) @ (index):80
(index):80 Error: Error: XHR error (404 Not Found) loading http://localhost:3002/ng2-validation(…)

**Comment by yuyang041060120** [comment]
please see v3.7.1, I had add `bundles/ng2-validation.umd.js` from system.js.
