### ISSUE TITLE
More custom/detailed error messages on failed validation

### ISSUE THREAD

**Issue by st-clair-clarke** [yuyang041060120/ng2-validation#12]
Hi Yu,
Congrats on a fine library. I was using validator.js (https://www.npmjs.com/package/validator) but had some event issues with it so yours is welcome.

3 requests please:
1) More detail message required from the validator

Consider your code below for min

/**
- Validator that requires controls to have a value of a min value.
  */
  static min(min: number): ValidatorFn {
    return (control: AbstractControl): {[key: string]: any} => {
      if (isPresent(Validators.required(control))) return null;
  
  ```
  let v: number = control.value;
  return v >= min ? null : {'min': true};
  ```
  
    };
  }

Instead of return {'min': true} when the validation failed, why not return

{'min': {'min': true, message: 'Minimun value ALLOWED is ${min}}

So we could access the error message like so: min.message or min['message']

Or you could simply return the message when the validation fails.

2) If you CANNOT do 1), would it be possible for you to expose an isMin(number) or its eqivalent to allow us to use it to generate out own custom messages

3) Any intention to expand your library to include other validators such as those in https://www.npmjs.com/package/validator?

Thanks and congrats again and let me know what you think,

**Comment by yuyang041060120** [comment]
First, Thank you for your attention. As for question 1 and 2 , you should know that this is a angular2 validation which follows framework design. As for question 3 , I will expand it in the future and welcome PR.

**Comment by st-clair-clarke** [comment]
Thank you very much.
