### ISSUE TITLE
Not working in angular-seed

### ISSUE THREAD

**Issue by Nikhil-Pahwa** [yuyang041060120/ng2-validation#13]
I tried integrating the ng2-validation in my angular-seed based project. 
for ref: https://github.com/mgechev/angular-seed
I am getting the following error when i import the CustomFormsModule. 

"(SystemJS) Unexpected token <
    SyntaxError: Unexpected token <
        at Object.eval (http://localhost:5555/node_modules/ng2-validation/dist/directives/range-length.js:13:10)
        at eval (http://localhost:5555/node_modules/ng2-validation/dist/directives/range-length.js:43:4)
        at eval (http://localhost:5555/node_modules/ng2-validation/dist/directives/range-length.js:44:3)
    Evaluating http://localhost:5555/node_modules/ng2-validation/dist/
    Evaluating http://localhost:5555/node_modules/ng2-validation/dist/directives/range-length.js
    Evaluating http://localhost:5555/node_modules/ng2-validation/dist/directives.js
    Evaluating http://localhost:5555/node_modules/ng2-validation/dist/index.js
    Evaluating http://localhost:5555/app/app.module.js
    Evaluating http://localhost:5555/app/main.js
    Error loading http://localhost:5555/app/main.js"

I am getting the same error for both template driven and reactive forms. Please help me in this regard.

**Comment by trevordaniels** [comment]
I think I have a similar problem with the advanced seed project, which extends this seed project. When running in dev mode, it manifests in the browser as 

`Error loading http://localhost:5555/node_modules/ng2-validation/dist/.js as ".." from http://localhost:5555/node_modules/ng2-validation/dist/directives/range.js`

or whatever validator is loaded first.

Its linked to this line in a few js files

`var _1 = require('../');`

I think systemjs is not automatically looking for index.js in this parent folder. The seed projects abstract slightly away from systemjs config and dont require direct editing of the config to load a package.

A workaround is to explicitly require index by changing all similar lines to

`var _1 = require('../index');`

**Comment by rramo012** [comment]
I ran into a similar problem. Adding the following 2 lines to my system config paths seemed to fix it for me.

'ng2-validation' : 'node_modules/ng2-validation/dist/index.js',
'ng2-validation/dist/' : 'node_modules/ng2-validation/dist/index.js'

**Comment by nxpatterns** [comment]
**PATHS:**

``` javascript
paths: {
      'ng2-validation' : 'node_modules/ng2-validation/dist/index.js',
      'ng2-validation/dist/*' : 'node_modules/ng2-validation/dist/*',
```

**PACKAGES:**
``` javascript
    packages: {
      'ng2-validation': {
        main: 'index',
        defaultExtension: 'js'
      },
      'ng2-validation/dist/': {
        main: 'index',
        defaultExtension: 'js'
      },
```

**Comment by yuyang041060120** [comment]
please see v3.7.1, I had add `bundles/ng2-validation.umd.js` from system.js.
