### ISSUE TITLE
equalTo doesn't set ng-invalid

### ISSUE THREAD

**Issue by brunsten** [yuyang041060120/ng2-validation#14]
First of all; lovely package. Brillant!
Im having a small issue when using this code (simplified) 

```
<div ngModelGroup="passwordGroup" equalTo>
    <label class="label" for="signUpPassword">Password</label>
    <input class="input" [(ngModel)]="signUpUser.password" id="signUpPassword" type="password" required #password/>
    <label class="label" for="signUpPasswordConfirm">Confirm password</label>
    <input class="input" [(ngModel)]="signUpUser.passwordConfirm" #passwordConfirm/>
</div>
<p *ngIf="signUpForm.form.controls.passwordGroup?.errors?.equalTo">equalTo error</p>
<p>password: {{password.className}}</p>
<p>passwordConfirm: {{passwordConfirm.className}}</p>
```

And the user inputs something that doesnt match, you get the 'equalTo error' but not the ng-invalid class on passwordConfirm/password

Screencapture includes some elements not displayed in example code
![image](https://cloud.githubusercontent.com/assets/6051448/19622617/cc9992b0-98ad-11e6-8a00-bf57cf9a706f.png)

Is this expected? It this a bug?

**Comment by IlyaSurmay** [comment]
I also have that issue. It's not really necessary because we can set some custom error class but it would be great to have ng-invalid class out of the box

**Comment by yuyang041060120** [comment]
@brunsten @IlyaSurmay please check the new version.
