### ISSUE TITLE
Not AOT Friendly

### ISSUE THREAD

**Issue by JesperWe** [yuyang041060120/ng2-validation#16]
As noted [here](https://github.com/angular/angular-cli/issues/2957) and in other places, Angular2 modules need some extra configs to work with Ahead of Time compilation. ng2-validation does not work with AoT, throwing a similar error to the others in the linked issue.

```
Error: Unexpected value 'CustomFormsModule' imported by the module 'AppModule'
    at /var/www/www.rf.se/node_modules/@angular/compiler/bundles/compiler.umd.js:14326:37
```

**Comment by spr1ne** [comment]
AOT Support #30 (Please merge it)
