### ISSUE TITLE
Can't handle dynamically changing validation values

### ISSUE THREAD

**Issue by robkrause** [yuyang041060120/ng2-validation#25]
If I use a dynamically changing validation value, the validation doesn't rerun. Even if I use `.updateValueAndValidity();`, the validation remains in it's old state.
Reassigning a new value with `CustomValidators.max(pagecount)` e.g. helps but is far from ideal.

Another directive from here [https://github.com/czeckd/angular2-minmax-validators/blob/master/app/minmax/min-value-validator.directive.ts](https://github.com/czeckd/angular2-minmax-validators/blob/master/app/minmax/min-value-validator.directive.ts) is able to handle such scenario since it triggers the validation on changes.

**Comment by yuyang041060120** [comment]
@robkrause please see the new version.
