### ISSUE TITLE
email regex validation doesn't work properly

### ISSUE THREAD

**Issue by mhmo91** [yuyang041060120/ng2-validation#27]
there's a problem with Email validation pattern is not working properly
expressions like x@x passes, where it shouldn't, firebase for ex. don't accept that format...

**Comment by chompy18** [comment]
I am seeing this too.
I suggest using this regex instead:
`^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$`

**Comment by sefininio** [comment]
I went ahead and created a PR for this:
https://github.com/yuyang041060120/ng2-validation/pull/29

**Comment by yuyang041060120** [comment]
release 3.0.2

**Comment by yuyang041060120** [comment]
@jsBlackBelt Thank you for your contributes, But please add your unit test before PR next time.
