### ISSUE TITLE
breaks in angular-cli: 1.0.0-beta.22-1

### ISSUE THREAD

**Issue by arfeifei** [yuyang041060120/ng2-validation#28]
**Error: CustomFormsModule is not an NgModule**
    at AotPlugin.getNgModuleMetadata (D:\Lab\Temp\MyProject\ng2\MyProject\node_modules\@ngtools\webpack\src\plugin.js:332:19)
    at D:\Lab\Temp\MyProject\ng2\MyProject\node_modules\@ngtools\webpack\src\plugin.js:345:51
    at Array.map (native)
    at AotPlugin.extractLoadChildren (D:\Lab\Temp\MyProject\ng2\MyProject\node_modules\@ngtools\webpack\src\plugin.js:343:14)
    at D:\Lab\Temp\MyProject\ng2\MyProject\node_modules\@ngtools\webpack\src\plugin.js:346:30
    at Array.map (native)
    at AotPlugin.extractLoadChildren (D:\Lab\Temp\MyProject\ng2\MyProject\node_modules\@ngtools\webpack\src\plugin.js:343:14)
    at AotPlugin._processNgModule (D:\Lab\Temp\MyProject\ng2\MyProject\node_modules\@ngtools\webpack\src\plugin.js:272:38)
    at D:\Lab\Temp\MyProject\ng2\MyProject\node_modules\@ngtools\webpack\src\plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by intellix** [comment]
I think this is actually a bug with angular-cli itself. I'm having these issues for a couple of modules and I see a few people with the same complaints in angular-cli/issues

**Comment by ddavid67** [comment]
Same issue here. Is there a way to fix it myself before next cli release ?

**Comment by SylTi** [comment]
You can downgrade to 1.0.0-beta.21

**Comment by intellix** [comment]
Been told that it's not an issue with angular-cli, but the project people are trying to import. The problem with angular-cli at the moment is that it doesn't give you the error as to why something isn't regarded as an NgModule. I believe beta 23 will at least give a bit more insight as to why it doesn't like some modules. 

This needs fixing in this repository, but as to why it doesn't like it, I guess we'll find out when we get our hands on 23

**Comment by manuelfink** [comment]
As it read in https://github.com/angular/angular-cli/issues/3426

> Please also take in mind, when building a production build with --aot.. That export default doesn't work!

also it is mentioned that 

> This is something to do with the thirdparty library. They are not statically analyzable; basically they don't publish metadata.json files which we need to understand their modules or components.

Quick fix for now, downgrading to angular-cli 1.0.0-beta.21

Unluckily I do not have any experiences with building libs and metadata.json however I hope this helps resolving the issue quickly.
