### ISSUE TITLE
指令能否配置在blur的时候才进行检查？

### ISSUE THREAD

**Issue by hbbbs** [yuyang041060120/ng2-validation#3]
ng2-validation提供了不少指令，比如：[rangeLength]="[5, 9]"

能否配置在blur的时候才进行检查？

**Comment by yuyang041060120** [comment]
@hbbbs 你好，校验的机制是由Angular2框架层面提供的，ng2-validation本身是控制不了的，也不属于该库的职责范围。

**Comment by hbbbs** [comment]
谢谢答复！
