### ISSUE TITLE
Add AoT compilation support in Angular-2

### ISSUE THREAD

**Issue by manuelfink** [yuyang041060120/ng2-validation#31]
Please add support for AoT compilation. It fails right now with the error 

`Unexpected value 'CustomFormsModule' imported by the module`

```
ng build --prod --env=prod --aot
10% building modules 2/2 modules 0 active Unexpected value 'CustomFormsModule' imported by the module 'MyModule'
```

I guess metadata.json files are missing from the library which are required by ngc.
Similar issue in [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap/issues/1350) 

I'm using angular-cli 1.0.0-beta.21 right now, since latest has some compiler issues as described in #28. But I believe this problem is independent from this. This may also solve #28

**Comment by jesmith17** [comment]
I am experiencing the same issue

**Comment by intellix** [comment]
PR: https://github.com/yuyang041060120/ng2-validation/pull/30

**Comment by intellix** [comment]
that PR was merged, can this be closed now?
