### ISSUE TITLE
min and max is not working correctly with input[text]

### ISSUE THREAD

**Issue by sabrio** [yuyang041060120/ng2-validation#35]
```
static min(min: number): ValidatorFn {
    return (control: AbstractControl): {[key: string]: any} => {
      if (isPresent(Validators.required(control))) return null;

      let v: number = control.value;
      console.log(typeof min);//string
      return v >= min ? null : {'min': true};
    };
  }
```
One solution would be to parseFloat(min)

**Comment by robgha01** [comment]
dont know if it is related but using min and only writing numerics in a password input results in validator not validating. so doing this:
`let password = this.formBuilder.control("", Validators.compose([Validators.required, CustomValidators.min(8)]));` and writing 123 in a input[Password] results in valid state...

however if i add a space or any character abc it validates.

**Comment by yuyang041060120** [comment]
try the latest version
