### ISSUE TITLE
ERROR in CustomFormsModule is not an NgModule

### ISSUE THREAD

**Issue by mhmo91** [yuyang041060120/ng2-validation#37]
I know this has been reported before, but i just need ASAP clarification if the problem is bug with the module implementation or it's an ng-cli / webpack bug?

I'm on those versions
"angular-cli": "1.0.0-beta.24",
"@angular/compiler-cli": "^2.3.1",
"typescript": "^2.0.10",
"@angular/common": "^2.3.1",

thanks

**Comment by spr1ne** [comment]
I think problem in AOT build, i create pull request which resolve this problem #30 .
And in my project i import CustomFormsModule directly from 'ng2-validation/dist/directives'.
