### ISSUE TITLE
CustomValidators.equalTo() reverse validation doesn't works 

### ISSUE THREAD

**Issue by Invis1ble** [yuyang041060120/ng2-validation#5]
When equalControl's value changes validation doesn't works.

**Comment by yuyang041060120** [comment]
@Invis1ble can you show more details?

**Comment by Invis1ble** [comment]
@yuyang041060120 I've created the demo http://plnkr.co/edit/zcgWZBPklcdSNbnIJOA6?p=preview
Try to add some chars into the "Retype Pasword" field. The error "Passwords missmatch" should appears. Then add the same chars into the "Password" field - the error "Passwords missmatch" should disappears, but it doesn't.
Or the second case: try to add some chars into the "Password" field. The error "Passwords missmatch" should appear, but it doesn't.

**Comment by yuyang041060120** [comment]
@Invis1ble I got your point. But I'm too busy these days. I will fix it as soon as possible. Thank you!

**Comment by BioSin** [comment]
@yuyang041060120 Hello, maybe I can implement this.. But I'm little bit in stuck with it.
What you think about [this solution](http://stackoverflow.com/questions/35474991/angular-2-form-validating-for-repeat-password) - wrap related controls into FormGroup? Looks nice.

**Comment by yuyang041060120** [comment]
@Invis1ble I fixed this bug. Maybe you can try again.

**Comment by BioSin** [comment]
@yuyang041060120 is it break backward compatibility? When I will update your library, will it breaking my existing code? If yes, maybe better to change version to 2.x according http://semver.org

**Comment by yuyang041060120** [comment]
@BioSin you are right! I corrected.

**Comment by Invis1ble** [comment]
@yuyang041060120 Sorry, I can't test it for now, but I think it should works.
Is it possible to use `equalTo` without wrapping inputs in a group?

**Comment by yuyang041060120** [comment]
@Invis1ble I'm afraid not. If you have any idea, maybe you can contact me.
