### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by zxc19890923** [yuyang041060120/ng2-validation#63]
您好 看起来就简单几步，我使用angular-cli创建项目  
1. 安装
2. 配置app.module.ts
3. 配置模板
4. 初始化变量

但是还是报错，请问还有其他东西需要安装，配置吗

**Comment by yuyang041060120** [comment]
先不要引入ng2-validation，然后启动项目看看是否报错。如果启动正常，引入ng2-validation后报错的话，还麻烦贴下报错信息

**Comment by zxc19890923** [comment]
恩 好了 谢谢

**Comment by yuyang041060120** [comment]
@zxc19890923 不客气
