### ISSUE TITLE
No angular 2.0.0 yet

### ISSUE THREAD

**Issue by onecib** [yuyang041060120/ng2-validation#7]
Hi,

Is there any way to use the ng2-validation without the CustomFormsModule ,
I dont use the ngModule yet , so i need a component and not the module.
I also tried to see in the history of your older commits but didnt find it .

Thanks.
Othman

**Comment by onecib** [comment]
can I use the CustomValidators for example ?

**Comment by yuyang041060120** [comment]
@xcuben You can use v1.3.0, It support Angular rc-4. You can use CustomValidators in any Angular version.

**Comment by onecib** [comment]
thanks yuyang041060120

**Comment by yuyang041060120** [comment]
You are welcome. Hope enjoy it.

**Comment by onecib** [comment]
@yuyang041060120  Thanks , its working right now.

i wanted to add some phone regex for germany in the customValidator via git but i've got a denied permission for pushing/committing my changes . may be you could add me to the white list or just add :
            'de-DE': /^(+?49|0)[1-9]\d{10}$/
in the list of phoneValidations 

thanks

**Comment by yuyang041060120** [comment]
@xcuben you can fork my repo and pull request.

**Comment by yuyang041060120** [comment]
@xcuben you can use v1.4.2 now.

**Comment by onecib** [comment]
@yuyang041060120 : thanks :)
