### ISSUE TITLE
Error, When building AOT with ng build --prod --aot

### ISSUE THREAD

**Issue by NomiJ** [yuyang041060120/ng2-validation#70]
This issue is happening on ubuntu, when trying to build AOT build. 

ERROR in /usr/src/app/my-app/src/$$_gendir/app/auth/auth.component.ngfactory.ts (597,168): Property 'required' does not exist on type '{ [key: string]: any; }'.

Depending upon which validation I used, Property changes to email, range length or e.t.c. 

I am using "@angular/cli": "^1.0.0-rc.1" and     "ng2-validation": "^3.1.3". 

Thanks

**Comment by BallisticPain** [comment]
@NomiJ Have you tried the latest version? 3.9.1 is the latest version of `ng2-validation`.

**Comment by NomiJ** [comment]
Thanks, upgrading the version. I don't see errors any more. On the side note, I see this
+-- UNMET PEER DEPENDENCY @angular/common@4.0.1
+-- UNMET PEER DEPENDENCY @angular/compiler@4.0.1
+-- UNMET PEER DEPENDENCY @angular/core@4.0.1
+-- UNMET PEER DEPENDENCY @angular/http@4.0.1
+-- UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.1
`-- ng2-validation@3.9.1 

I am not sure if it actually mean that ng2-validation does not support angular 4.0.1 or not. Kindly let me know. 

Thanks

**Comment by yuyang041060120** [comment]
Don't worry. It works well.
